name: Unit tests for source files
on: [push]


jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install required packages
        run: sudo $GITHUB_WORKSPACE/.ci_scripts/install_packages.sh

      - name: Build project with CMake
        run: $GITHUB_WORKSPACE/.ci_scripts/build.sh -d $GITHUB_WORKSPACE

      - name: Run CUnit tests
        run: $GITHUB_WORKSPACE/.ci_scripts/run_tests.sh

      - name: Run Valgrind on CUnit tests
        run: $GITHUB_WORKSPACE/.ci_scripts/run_tests.sh valgrind

      - name: Run cppcheck on source files
        run: $GITHUB_WORKSPACE/.ci_scripts/run_cppcheck.sh
